games_list = [
    [1,
    "Super Mario Bros",
    "Sep 13, 1985",
    'A side scrolling 2-D platformer that follows Italian Plumber Mario as he ventures across a variety of challenges to rescue Princess Peach from the king of the koopas, Bowser ',
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co2362.jpg',
    'https://mario.nintendo.com/',
    [1,2,15],
    [1,2,5,6,7,9,10,12],
    None,
    'https://www.amazon.com/Super-Mario-Bros-nintendo-entertainment-system/dp/B00004SVV7/ref=sr_1_8?dchild=1&keywords=Super+Mario+Bros+NES&qid=1626301037&s=videogames&sr=1-8',
    'https://www.gamestop.com/video-games/retro-gaming/nintendo/games/products/super-mario-bros./10125269.html',
    'https://www.bestbuy.com/site/super-mario-bros-nintendo-wii-u-digital/6027403.p?skuId=6027403'
    ],
    [2,
    "Hades",
    "Sep 17, 2020",
    'A rogue-lite hack and slash game where Zagreus, son of Hades, tries to escape his home, through fighting the souls of the dead across several layers pf the underworld.',
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co39vc.jpg',
    'https://www.supergiantgames.com/games/hades/',
    [1,2,7,9],
    [7,16,17,20,21,22,23],
    'https://store.steampowered.com/app/1145360/Hades/',
    'https://www.amazon.com/s?k=hades+game&i=videogames&ref=nb_sb_noss_1',
    'https://www.gamestop.com/video-games/nintendo-switch/games/products/hades---nintendo-switch/11110524.html',
    'https://www.bestbuy.com/site/hades-nintendo-switch-nintendo-switch-lite/6414094.p?skuId=6414094'
    ],
    [3,
    "Super Mario World",
    "Nov 21, 1990",
    'A 2-D platformer and the first entry of the Super Mario series on SNES, Super Mario World involves Mario yet again battling through Bowser and his minions as he seeks to rescue Princess Peach.',
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co2v5y.jpg',
    'https://mario.nintendo.com/',
    [1,2,15],
    [2,5,6,7,9,10,12],
    None,
    'https://www.amazon.com/Super-Mario-World-Nintendo/dp/B00002STXQ',
    'https://www.gamestop.com/video-games/retro-gaming/super-nintendo/games/products/super-mario-world/10125270.html',
    None
    ],
    [4,
    "Halo: Combat Evolved",
    "Nov 15, 2001",
    'Under attack by a fellowship of alien races known as the Covenant, Earth turns to the Master Chief, a member of a biologically altered super-soldiers known as Spartans. Follow the Chief as you battle the Covenant on an ancient Ring-World known as Halo.',
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r2r.jpg',
    'https://www.halowaypoint.com/en-us/games/halo-combat-evolved',
    [1,10],
    [18,19,22,23],
    'https://store.steampowered.com/app/1064221/Halo_Combat_Evolved_Anniversary/',
    'https://www.amazon.com/Halo-Combat-Evolved-Not-Resale-Xbox/dp/B00005NZ1G',
    'https://www.gamestop.com/video-games/retro-gaming/xbox/games/products/halo-combat-evolved/10152638.html',
    None
    ],
    [5,
    "Final Fantasy VII",
    "Jan 31, 1997",
    "The seventh main game in the Final Fantasy Series, the first 3D game of the series. Follow Cloud and a unique cast of characters as they take on the mega-conglomerate Shinra who has been destroying the surface of planet absorbing Mako energy. Can Cloud and the AVALANCHE rebel group protect the planet from Shinra Inc.?",
    "https://images.igdb.com/igdb/image/upload/t_cover_big/co2kx2.jpg",
    "https://finalfantasyviipc.square-enix-games.com/",
    [2,9],
    [7,13,16,20,22],
    'https://store.steampowered.com/app/39140/FINAL_FANTASY_VII/',
    'https://www.amazon.com/Final-Fantasy-VII-Playstation/dp/B00000JRSB',
    'https://www.gamestop.com/video-games/retro-gaming/playstation/games/products/final-fantasy-vii/10122345.html',
    'https://www.bestbuy.com/site/shop/final-fantasy-vii'
    ],
    [6,
    "Pokemon Blue",
    "Oct 15, 1996",
    "Apart of the now 1st generation of pokemon games. Begin your journey as a pokemon trainer as you collect a wide variety of pokemon, battle other trainers, and push your way to the Pokemon League!",
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co2s5u.jpg',
    'https://www.pokemon.com/us/pokemon-video-games/pokemon-red-version-and-pokemon-blue-version/',
    [2,9],
    [8,9,12],
    None,
    'https://www.amazon.com/Pokemon-Blue-Version-Nintendo-Game-Boy/dp/B00000IYER',
    'https://www.gamestop.com/video-games/retro-gaming/game-boy/games/products/pokemon-blue-version/10129625.html',
    'https://www.bestbuy.com/site/pokemon-blue-version-standard-edition-nintendo-3ds-digital/4856300.p?skuId=4856300'
    ],
    [7,
    "Ratchet & Clank: Rift Apart",
    "Jun 11, 2021",
    "Ratchet and Clank take on an evil empire as they go on a dimension hopping journey through action packed worlds.",
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co2str.jpg',
    'https://insomniac.games/game/ratchet-clank-rift-apart/',
    [2,10,15],
    [17],
    None,
    'https://www.amazon.com/Ratchet-Clank-Rift-Apart-PlayStation-5/dp/B095T8C99C',
    'https://www.gamestop.com/video-games/playstation-5/games/products/ratchet-and-clank-rift-apart---playstation-5/11118328.html',
    'https://www.bestbuy.com/site/ratchet-clank-rift-apart-launch-edition-playstation-5/6430758.p?skuId=6430758'
    ],
    [8,
    'The Legend of Zelda: Ocarina of Time',
    'Nov 21, 1998',
    "Follow Link as he treks across Hyrule, ventures into treacherous dungeons, and travels through time in order to save the land from the evil Ganondorf.",
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co2twe.jpg',
    'https://www.nintendo.com/games/detail/the-legend-of-zelda-ocarina-of-time-wii-u/',
    [2,9,13,15],
    [3,4,5,6],
    None,
    'https://www.amazon.com/Legend-Zelda-Ocarina-Time-nintendo-64/dp/B00000DMB3',
    'https://www.gamestop.com/video-games/retro-gaming/nintendo-64/games/products/the-legend-of-zelda-ocarina-of-time/10122505.html',
    'https://www.bestbuy.com/site/nintendo-selects-the-legend-of-zelda-ocarina-of-time-3d-nintendo-3ds-digital/6220257.p?skuId=6220257'
    ],
    [9,
    'God of War (2018)',
    'Apr 20,2018',
    'In a new and unfamilar land within Norse mythology, with his son at his side, he must fight for survival and to protect the new life he has made.',
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmu.jpg',
    'https://godofwar.playstation.com/',
    [1,2],
    [16],
    None,
    'https://www.amazon.com/God-War-Playstation-4/dp/B01GW8XOY2',
    'https://www.gamestop.com/video-games/playstation-4/games/products/god-of-war/10131619.html',
    'https://www.bestbuy.com/site/god-of-war-playstation-hits-standard-edition-playstation-4/5358600.p?skuId=5358600'
    ],
    [10,
    'Super Mario 64',
    'Jun 23, 1996',
    "The first 3D Mario game, follow Mario has he jumps into worlds-within-paintings on the walls of Peach's Castle as he seeks to rescue her from Bowser's clutches.",
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co21mm.jpg',
    'https://www.nintendo.com/games/detail/super-mario-64-wii-u/',
    [15],
    [3,5,6,7],
    None,
    'https://www.amazon.com/Super-Nintendo-Version-No-Operating-System/dp/B085RF4L6P/ref=pd_lpo_63_t_0/140-8925305-5348950?_encoding=UTF8&pd_rd_i=B085RF4L6P&pd_rd_r=3d64235d-241a-4c15-86ad-189e13aad2ae&pd_rd_w=Xq7tz&pd_rd_wg=bpYBa&pf_rd_p=fb1e266d-b690-4b4f-b71c-bd35e5395976&pf_rd_r=C5KNC3NQ5PR5GK2XXJ7C&psc=1&refRID=C5KNC3NQ5PR5GK2XXJ7C',
    'https://www.gamestop.com/video-games/retro-gaming/nintendo-64/games/products/super-mario-64/10122543.html',
    'https://www.bestbuy.com/site/super-mario-64-nintendo-wii-u-digital/5924504.p?skuId=5924504'
    ],
    [11,
    'Hollow Knight',
    'Feb 24, 2017',
    "A 2D Metroidvania style game in which the player travels through Hallownest, a now-bleak insect kingdom and uncovers its history while battling enemies and bosses, while also meeting some friendly inhabitants.",
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rgi.jpg',
    'https://www.hollowknight.com/',
    [2,7,15],
    [7,22,23,24],
    'https://store.steampowered.com/app/367520/Hollow_Knight/',
    'https://www.amazon.com/Hollow-Knight-Nintendo-Switch/dp/B07SG7MQZF',
    'https://www.gamestop.com/video-games/nintendo-switch/games/products/hollow-knight/10174149.html',
    'https://www.bestbuy.com/site/hollow-knight-nintendo-switch/6338790.p?skuId=6338790'
    ],
    [
        12,
        "Persona 4: Golden",
        'Jun 15, 2012',
        'An ennhanced version of Persona 4, where you must solve the mystery behind a string of murders in a small town during a mysterious fog.',
        'https://images.igdb.com/igdb/image/upload/t_cover_big/co1n1x.jpg',
        'https://atlus.com/atlus-titles/persona4-golden/?ItemID=26#upcp-user-tab-panel-1/',
        [2,9,11],
        [22],
        "https://store.steampowered.com/app/1113000/Persona_4_Golden/",
        None,
        None,
        None
    ],
    [13,
    "The Witcher 3: Wild Hunt",
    "May 19, 2015",
    'Continue your adventures as Geralt as he searches for Ciri across several regions. Work with or against characters new and old as you try to stop the Wild Hunt from capturing Ciri.',
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg',
    'https://www.thewitcher.com/en',
    [1,2,9],
    [7,16,20,22],
    "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
    'https://www.amazon.com/Witcher-Wild-Hunt-Complete-PlayStation-4/dp/B01K6010FM',
    'https://www.gamestop.com/video-games/playstation-4/games/products/the-witcher-iii-wild-hunt/10113676.html',
    'https://www.bestbuy.com/site/the-witcher-3-wild-hunt-complete-edition-nintendo-switch/6352296.p?skuId=6352296'
    ],
    [14,
    'The Last of Us',
    'Jun 14, 2013',
    'A third person action/stealth shooter taking place 20 years after an outbreak of a parasitic fungus, where as Joel, you smuggle fourteen year old Ellie to a group known as the Fireflies. Fight for survival against strict authoritities, infected, and other violent survivors.',
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7f.jpg',
    'https://www.playstation.com/en-us/games/the-last-of-us-remastered/',
    [1,2,10],
    [15,16],
    None,
    'https://www.amazon.com/Last-Us-Remastered-PlayStation-4/dp/B00JK00S0S',
    'https://www.gamestop.com/video-games/playstation-4/games/products/the-last-of-us-remastered/10114511.html',
    'https://www.bestbuy.com/site/the-last-of-us-remastered-playstation-hits-playstation-4/5875178.p?skuId=5875178'
    ],
    [15,
    'Bloodbourne',
    'May 24,2015',
    'Play as a Hunter who after being transfused with blood local to the city of Yharnam, sets off to thin the population of beasts that plague the city.',
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rba.jpg',
    'https://www.playstation.com/en-us/games/bloodborne/',
    [1,2,9],
    [16],
    None,
    'https://www.amazon.com/Bloodborne-PlayStation-4/dp/B00KVR4HEC',
    'https://www.gamestop.com/video-games/playstation-4/games/products/bloodborne/10115480.html',
    'https://www.bestbuy.com/site/bloodborne-playstation-hits-playstation-4/7314019.p?skuId=7314019'
    ],
    [16,
    'Star Wars: Knights of the Old Republic',
    'Jul 15, 2003',
    'The last hope for the Jedi Order and the Republic will you master the light side of the force and save them? Or fall to the dark side and bring chaos',
    'https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmz.jpg',
    'https://www.starwars.com/games-apps/knights-of-the-old-republic',
    [1,2,9],
    [18,22,23],
    'https://store.steampowered.com/app/32370/STAR_WARS__Knights_of_the_Old_Republic/',
    'https://www.amazon.com/Star-Wars-Knights-Old-Republic-Xbox/dp/B000067DPM',
    'https://www.gamestop.com/video-games/retro-gaming/xbox/games/products/star-wars-knights-of-the-old-republic/10021673.html',
    None
    ]












    
]



